// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: dracula.proto

package dracula

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExportHealthHttpServiceClient is the client API for ExportHealthHttpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExportHealthHttpServiceClient interface {
	ExportHealth(ctx context.Context, in *ExportHealthDataRequest, opts ...grpc.CallOption) (*ExportHealthDataResponse, error)
}

type exportHealthHttpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExportHealthHttpServiceClient(cc grpc.ClientConnInterface) ExportHealthHttpServiceClient {
	return &exportHealthHttpServiceClient{cc}
}

func (c *exportHealthHttpServiceClient) ExportHealth(ctx context.Context, in *ExportHealthDataRequest, opts ...grpc.CallOption) (*ExportHealthDataResponse, error) {
	out := new(ExportHealthDataResponse)
	err := c.cc.Invoke(ctx, "/grpc.apple_health_monitor.dracula.ExportHealthHttpService/ExportHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExportHealthHttpServiceServer is the server API for ExportHealthHttpService service.
// All implementations should embed UnimplementedExportHealthHttpServiceServer
// for forward compatibility
type ExportHealthHttpServiceServer interface {
	ExportHealth(context.Context, *ExportHealthDataRequest) (*ExportHealthDataResponse, error)
}

// UnimplementedExportHealthHttpServiceServer should be embedded to have forward compatible implementations.
type UnimplementedExportHealthHttpServiceServer struct {
}

func (UnimplementedExportHealthHttpServiceServer) ExportHealth(context.Context, *ExportHealthDataRequest) (*ExportHealthDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportHealth not implemented")
}

// UnsafeExportHealthHttpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExportHealthHttpServiceServer will
// result in compilation errors.
type UnsafeExportHealthHttpServiceServer interface {
	mustEmbedUnimplementedExportHealthHttpServiceServer()
}

func RegisterExportHealthHttpServiceServer(s grpc.ServiceRegistrar, srv ExportHealthHttpServiceServer) {
	s.RegisterService(&ExportHealthHttpService_ServiceDesc, srv)
}

func _ExportHealthHttpService_ExportHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportHealthDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportHealthHttpServiceServer).ExportHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.apple_health_monitor.dracula.ExportHealthHttpService/ExportHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportHealthHttpServiceServer).ExportHealth(ctx, req.(*ExportHealthDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExportHealthHttpService_ServiceDesc is the grpc.ServiceDesc for ExportHealthHttpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExportHealthHttpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.apple_health_monitor.dracula.ExportHealthHttpService",
	HandlerType: (*ExportHealthHttpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExportHealth",
			Handler:    _ExportHealthHttpService_ExportHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dracula.proto",
}
